from pathlib import Path

path = Path("PingerApp/PingerApp.py")
text = path.read_text(encoding="utf-8")

text = text.replace(
'''        self.route_diagnosis_box = None\n        self.route_raw_box = None\n''',
'''        self.route_diagnosis_box = None\n        self.route_speed_details_box = None\n        self.route_raw_box = None\n        self.route_raw_toggle_btn = None\n''', 1)

marker = '''    def show_port_check_window(self):\n'''
helpers = '''    def _make_hidden_details_group(self, title: str, button_text: str, line_wrap=QTextEdit.WidgetWidth, min_height=130):\n        group = QGroupBox(title)\n        group_layout = QVBoxLayout()\n        toggle = QPushButton(button_text)\n        toggle.setCheckable(True)\n        box = QTextEdit()\n        box.setReadOnly(True)\n        box.setMinimumHeight(min_height)\n        box.setLineWrapMode(line_wrap)\n        box.setVisible(False)\n\n        def toggle_details(checked):\n            box.setVisible(checked)\n            toggle.setText(("Hide " if checked else "Show ") + button_text.removeprefix("Show ").removeprefix("Hide "))\n\n        toggle.toggled.connect(toggle_details)\n        group_layout.addWidget(toggle)\n        group_layout.addWidget(box)\n        group.setLayout(group_layout)\n        return group, toggle, box\n\n    def _format_librespeed_details(self, raw_text: str):\n        try:\n            data = json.loads(raw_text or "{}")\n        except (TypeError, json.JSONDecodeError):\n            return "Speed-test details unavailable."\n        if isinstance(data, list):\n            data = data[0] if data else {}\n        if not isinstance(data, dict):\n            return "Speed-test details unavailable."\n\n        server = data.get("server", {}) or {}\n        lines = []\n        server_name = server.get("name") or "N/A"\n        server_url = server.get("url") or server.get("server")\n        lines.append(f"Server: {server_name}")\n        if server_url:\n            lines.append(f"Server URL: {server_url}")\n        timestamp = data.get("timestamp")\n        if timestamp:\n            lines.append(f"Test Time: {self._format_timestamp(timestamp)}")\n        if data.get("ping") is not None:\n            lines.append(f"Latency: {float(data.get('ping')):.2f} ms")\n        if data.get("jitter") is not None:\n            lines.append(f"Jitter: {float(data.get('jitter')):.2f} ms")\n        if data.get("download") is not None:\n            lines.append(f"Download: {format_mbps(data.get('download'))}")\n        if data.get("upload") is not None:\n            lines.append(f"Upload: {format_mbps(data.get('upload'))}")\n        if data.get("bytes_received") is not None:\n            lines.append(f"Data Received: {format_bytes_decimal(data.get('bytes_received'))}")\n        if data.get("bytes_sent") is not None:\n            lines.append(f"Data Sent: {format_bytes_decimal(data.get('bytes_sent'))}")\n        return "\\n".join(lines) if lines else "No speed-test details available."\n\n'''
if marker not in text:
    raise SystemExit("helper insertion marker not found")
text = text.replace(marker, helpers + marker, 1)

replacements = [
('''            raw_group = QGroupBox("Raw iperf3 JSON")\n            raw_layout = QVBoxLayout()\n            self.lan_raw_box = QTextEdit()\n            self.lan_raw_box.setReadOnly(True)\n            self.lan_raw_box.setMinimumHeight(130)\n            self.lan_raw_box.setLineWrapMode(QTextEdit.NoWrap)\n            raw_layout.addWidget(self.lan_raw_box)\n            raw_group.setLayout(raw_layout)\n            layout.addWidget(raw_group, 1)\n''', '''            raw_group, self.lan_raw_toggle_btn, self.lan_raw_box = self._make_hidden_details_group(\n                "Technical Details", "Show raw iperf3 JSON", QTextEdit.NoWrap, 130\n            )\n            layout.addWidget(raw_group)\n'''),
('''            raw_group = QGroupBox("Ping Log")\n            raw_layout = QVBoxLayout()\n            self.gateway_raw_box = QTextEdit()\n            self.gateway_raw_box.setReadOnly(True)\n            self.gateway_raw_box.setMinimumHeight(160)\n            self.gateway_raw_box.setLineWrapMode(QTextEdit.WidgetWidth)\n            raw_layout.addWidget(self.gateway_raw_box)\n            raw_group.setLayout(raw_layout)\n            layout.addWidget(raw_group, 1)\n''', '''            raw_group, self.gateway_raw_toggle_btn, self.gateway_raw_box = self._make_hidden_details_group(\n                "Technical Details", "Show ping log", QTextEdit.WidgetWidth, 160\n            )\n            layout.addWidget(raw_group)\n'''),
('''            raw_group = QGroupBox("Ping Log / Speed Test JSON")\n            raw_layout = QVBoxLayout()\n            self.route_raw_box = QTextEdit()\n            self.route_raw_box.setReadOnly(True)\n            self.route_raw_box.setMinimumHeight(150)\n            self.route_raw_box.setLineWrapMode(QTextEdit.WidgetWidth)\n            raw_layout.addWidget(self.route_raw_box)\n            raw_group.setLayout(raw_layout)\n            layout.addWidget(raw_group, 1)\n''', '''            speed_details_group = QGroupBox("Speed Test Details")\n            speed_details_layout = QVBoxLayout()\n            self.route_speed_details_box = QTextEdit()\n            self.route_speed_details_box.setReadOnly(True)\n            self.route_speed_details_box.setMaximumHeight(150)\n            self.route_speed_details_box.setLineWrapMode(QTextEdit.WidgetWidth)\n            self.route_speed_details_box.setPlaceholderText("Readable speed-test details will appear here.")\n            speed_details_layout.addWidget(self.route_speed_details_box)\n            speed_details_group.setLayout(speed_details_layout)\n            layout.addWidget(speed_details_group)\n\n            raw_group, self.route_raw_toggle_btn, self.route_raw_box = self._make_hidden_details_group(\n                "Technical Details", "Show probe log / raw LibreSpeed output", QTextEdit.WidgetWidth, 150\n            )\n            layout.addWidget(raw_group)\n'''),
('''        if self.route_diagnosis_box is not None:\n            self.route_diagnosis_box.clear()\n        if self.route_raw_box is not None:\n            self.route_raw_box.clear()\n''', '''        if self.route_diagnosis_box is not None:\n            self.route_diagnosis_box.clear()\n        if self.route_speed_details_box is not None:\n            self.route_speed_details_box.clear()\n        if self.route_raw_box is not None:\n            self.route_raw_box.clear()\n'''),
('''        if self.route_diagnosis_box is not None:\n            self.route_diagnosis_box.setPlainText(result.get("diagnosis", "N/A"))\n        if self.route_raw_box is not None:\n            self.route_raw_box.append("")\n            self.route_raw_box.append("LibreSpeed JSON:")\n            self.route_raw_box.append(result.get("speed_raw", ""))\n''', '''        if self.route_diagnosis_box is not None:\n            self.route_diagnosis_box.setPlainText(result.get("diagnosis", "N/A"))\n        if self.route_speed_details_box is not None:\n            self.route_speed_details_box.setPlainText(self._format_librespeed_details(result.get("speed_raw", "")))\n        if self.route_raw_box is not None:\n            self.route_raw_box.append("")\n            self.route_raw_box.append("Raw LibreSpeed output:")\n            self.route_raw_box.append(result.get("speed_raw", ""))\n'''),
('''            raw_group = QGroupBox("Raw Wi-Fi Command Output")\n            raw_layout = QVBoxLayout()\n            self.wifi_raw_box = QTextEdit()\n            self.wifi_raw_box.setReadOnly(True)\n            self.wifi_raw_box.setMinimumHeight(150)\n            self.wifi_raw_box.setLineWrapMode(QTextEdit.WidgetWidth)\n            raw_layout.addWidget(self.wifi_raw_box)\n            raw_group.setLayout(raw_layout)\n            layout.addWidget(raw_group, 1)\n''', '''            raw_group, self.wifi_raw_toggle_btn, self.wifi_raw_box = self._make_hidden_details_group(\n                "Technical Details", "Show raw Wi-Fi command output", QTextEdit.WidgetWidth, 150\n            )\n            layout.addWidget(raw_group)\n'''),
('''            raw_group = QGroupBox("Ping Log / Speed Test JSON")\n            raw_layout = QVBoxLayout()\n            self.loaded_raw_box = QTextEdit()\n            self.loaded_raw_box.setReadOnly(True)\n            self.loaded_raw_box.setMinimumHeight(170)\n            self.loaded_raw_box.setLineWrapMode(QTextEdit.WidgetWidth)\n            raw_layout.addWidget(self.loaded_raw_box)\n            raw_group.setLayout(raw_layout)\n            layout.addWidget(raw_group, 1)\n''', '''            raw_group, self.loaded_raw_toggle_btn, self.loaded_raw_box = self._make_hidden_details_group(\n                "Technical Details", "Show ping log / raw LibreSpeed output", QTextEdit.WidgetWidth, 170\n            )\n            layout.addWidget(raw_group)\n'''),
('''            raw_group = QGroupBox("Raw Ping Output")\n            raw_layout = QVBoxLayout()\n            self.mtu_raw_box = QTextEdit()\n            self.mtu_raw_box.setReadOnly(True)\n            self.mtu_raw_box.setLineWrapMode(QTextEdit.WidgetWidth)\n            raw_layout.addWidget(self.mtu_raw_box)\n            raw_group.setLayout(raw_layout)\n            layout.addWidget(raw_group, 1)\n''', '''            raw_group, self.mtu_raw_toggle_btn, self.mtu_raw_box = self._make_hidden_details_group(\n                "Technical Details", "Show raw ping output", QTextEdit.WidgetWidth, 150\n            )\n            layout.addWidget(raw_group)\n'''),
('''            self.trace_raw_box = QTextEdit()\n            self.trace_raw_box.setReadOnly(True)\n            self.trace_raw_box.setMinimumHeight(120)\n            self.trace_raw_box.setPlaceholderText("Raw traceroute output will appear here.")\n            layout.addWidget(self.trace_raw_box, 1)\n''', '''            raw_group, self.trace_raw_toggle_btn, self.trace_raw_box = self._make_hidden_details_group(\n                "Technical Details", "Show raw traceroute output", QTextEdit.WidgetWidth, 120\n            )\n            self.trace_raw_box.setPlaceholderText("Raw traceroute output will appear here.")\n            layout.addWidget(raw_group)\n'''),
]

for old, new in replacements:
    if old not in text:
        raise SystemExit(f"Expected diagnostic raw-output block not found: {old[:90]!r}")
    text = text.replace(old, new, 1)

path.write_text(text, encoding="utf-8")
